
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-4000}:8080
    networks:
      - api
    volumes:
      - pb_data:/pb/pb_data
      - ./server/pb_migrations:/pb/pb_migrations

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - SERVER_URL=${SERVER_URL}
    environment:
      SERVER_URL: http://server:8080
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT:-3000}:3000
    networks:
      - api
    depends_on:
      - server

networks:
  api:

volumes:
  pb_data: