
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - api

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT:-3000}:3000
    networks:
      - api
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      - server

networks:
  api:

volumes:
  node_modules: