

fragment BaseProductFragment on Product {
    id
    name
    price
    category {
        id
        name
    }
    country {
        id
        name
    }
    discount
    discountPrice
    unit
    quantityPerUnit
}