

fragment BaseProductFragment on Product {
    id
    name
    price
    category {
        id
        name
    }
    country {
        id
        name
    }
    discount
    published_at
    created_at
    updated_at
    unit
    measure
}