#import "./ProductFragment.gql"

query CartQuery {
    carts {
        id
        qty
        inOrder
        product {
            ...ProductFragment
        }
    }
}


mutation CreateCartMutation(
    $qty: Float!
    $product: ID!
) {
    createCart(input: {
        data: {
            product: $product
            qty: $qty
        }
    }) {
        cart {
            id
            qty
        }
    }
}

mutation DeleteCartMutation($id: ID!) {
    deleteCart(input: {
        where: { id: $id }
    }) {
        cart {
            updated_at
        }
    }
}

mutation UpdateCartMutation(
    $qty: Float
    $inOrder: Boolean
    $id: ID!
) {
    updateCart(input: {
        data: { qty: $qty, inOrder: $inOrder }
        where: { id: $id }
    }) {
        cart {
            updated_at
        }
    }
}
