            
            
mutation CreateOrderMutation(
    $email: String!, 
    $name: String!, 
    $surname: String!, 
    $address: String!, 
    $phone: String!
    $orderedProducts: [ComponentOrderOrderedProductInput]
) {
    createOrder(input: {
        data: {
            orderedProducts: $orderedProducts
            email: $email
            name: $name
            surname: $surname
            address: $address
            phone: $phone
        }
    }) {
        order {
            id
        }
    }
}