#import "./HeroFragment.gql"
#import "./ProductPreviewFragment.gql"
#import "./FeaturesFragment.gql"


query IndexPageQuery {
    hero {
        ...HeroFragment
    }

    newProducts: products(limit: 6, sort: "id:desc") {
        ...ProductPreviewFragment
    }

    discountProducts: products(limit: 6, sort: "discount:desc") {
        ...ProductPreviewFragment
    }
    
    features {
        ...FeaturesFragment
    }
}