#import "./HeroFragment.gql"
#import "./ProductPreviewFragment.gql"
#import "./FeaturesFragment.gql"


query IndexPageQuery {
    hero {
        ...HeroFragment
    }

    newProducts: products(limit: 8) {
        ...ProductPreviewFragment
    }
    
    features {
        ...FeaturesFragment
    }
}