#import "./UserFragment.gql"


mutation LogInMutation($identifier: String!, $password: String!) {
    data: login(input: { identifier: $identifier, password: $password }) {
        jwt
        user {
            ...UserFragment
        }
    }
}