#import "./ProductPreviewFragment.gql"


fragment OrderFragment on Order {
    id
    uid
    status
    email
    name
    surname
    address
    phone
    createdAt: created_at
    updatedAt: updated_at
    orderedProducts {
        id
        qty
        product {
            ...ProductPreviewFragment
        }
    }
}

query OrderQuery($id: ID!) {
    order( id: $id ) {
        ...OrderFragment
    }
}

query OrdersQuery {
    orders {
        ...OrderFragment
    }
}

mutation CreateOrderMutation(
    $email: String!, 
    $name: String!, 
    $surname: String!, 
    $address: String!, 
    $phone: String!
    $orderedProducts: [ComponentOrderOrderedProductInput]
) {
    createOrder(input: {
        data: {
            orderedProducts: $orderedProducts
            email: $email
            name: $name
            surname: $surname
            address: $address
            phone: $phone
        }
    }) {
        order {
            id
        }
    }
}

mutation DeleteOrderMutation(
    $id: ID!
) {
    deleteOrder(input: { where : { id: $id }}) {
        order {
            id
        }
    }
}
