#import "./ProductPreviewFragment.gql"


query OrderQuery($id: ID!) {
    order( id: $id ) {
        id
        uid
        status
        email
        name
        surname
        address
        phone
        orderedProducts {
            id
            qty
            product {
                ...ProductPreviewFragment
            }
        }
        user {
            id
            username
            email
        }
    }
}