#import "./ProductPreviewFragment.gql"


query OrdersQuery {
    orders {
        id
        status
        address
        email
        orderedProducts {
            id
            qty
            product {
                ...ProductPreviewFragment
            }
        }
    }
}