#import "./StrapiImageFragment.gql"
#import "./BaseProductFragment.gql"

fragment ProductFragment on Product {
    ...BaseProductFragment
    description
    images {
        ...StrapiImageFragment
    }
}