#import "./ProductPreviewFragment.gql"


query productPageQuery(
        $country: String,
        $category: String,
        $sort: String = "id:desc"
        $offset: Int
    ) {
    products(
        where: {
            category: { name: $category }
            country: { name: $country }
        }
        limit: 8
        start: $offset
        sort: $sort
    ) {
        ...ProductPreviewFragment
    }
}