#import "./ProductPreviewFragment.gql"


query productPageQuery($country: String, $category: String) {
    products(where: {
        category: { name: $category }
        country: { name: $country }
    }) {
        ...ProductPreviewFragment
    }
}