

mutation UpdatePasswordMutation (
    $password: String
    $oldPassword: String
) {
    updateUser(
        input: {
            data: {
                oldPassword: $oldPassword
                password: $password
            }
        }
    ) {
        user { id }
    }
}